New feat : Upload image in torrent upload page & torrent detail
tdjsnelling/sqtracker pull request #60
Opened 2023-10-11 15:01 UTC by Klaiment

With this update, here are the points that have been modified/added:

1. Fixed a Docker bug that prevented the correct mounting of the config.js file with Docker by explicitly indicating that it is a file and not a directory.

2. Added the image upload functionality requested in this report:
[link to the report](https://github.com/tdjsnelling/sqtracker/issues/14)

3. Also visible on the torrent detail page.

4. Added the French locales.

2023-10-12 10:10 UTC, tdjsnelling requested changes

2023-10-12 10:10 UTC, tdjsnelling commented on client/pages/torrent/[infoHash].js
> +  function isPngImage(data) {
Please follow existing code style here and include blank lines before & after function

2023-10-12 10:10 UTC, tdjsnelling commented on client/pages/torrent/[infoHash].js
> +      <Infobox mb={5}>
This InfoBox should only be shown if `torrent.poster` exists, the same as the media info box

2023-10-12 10:10 UTC, tdjsnelling commented on client/pages/torrent/[infoHash].js
> +      {console.log(torrent)}
Please remove

2023-10-12 10:10 UTC, tdjsnelling commented on client/pages/upload.js
> +          // Gérer les erreurs, si nécessaire
Please remove any French comments

2023-10-12 10:10 UTC, tdjsnelling commented on client/pages/upload.js
> +        <Box mb={4}>
Please make this field optional. Currently I cannot submit the form if I do not upload an image. Please also move the field down to the bottom of the form, above tags

2023-10-12 10:10 UTC, tdjsnelling commented on config.example.js
> +    SQ_BASE_URL: "http://localhost",
Please revert changes to this file. This file is to serve as a production example, using localhost here is incorrect

2023-10-12 10:10 UTC, tdjsnelling commented on docker-compose.dev.yml
> +      - "0.0.0.0:27017:27017"
Please revert

2023-10-12 10:10 UTC, tdjsnelling commented on client/pages/torrent/[infoHash].js
> +        <Text fontWeight={600} fontSize={1} textTransform="uppercase" mb={3}>
Text style is incorrect here, please observe how `textTransform` is applied on the other headings

2023-10-12 10:10 UTC, tdjsnelling commented on client/pages/upload.js
> +  const {
Please add a sensible max. file size for this upload

2023-10-12 10:10 UTC, tdjsnelling commented on client/pages/upload.js
> +      form.append("poster", posterFile.b64); // Ajoutez la valeur de l'image de l'affiche à la requête
Does this need to be appended to the form when you are submitting it below in the fetch request?

2023-10-12 10:38 UTC, Klaiment commented on api/src/controllers/torrent.js
> +        poster: 1,
The poster is retrieved on the torrent page so I need to retrieve it here

2023-10-12 10:48 UTC, tdjsnelling commented on api/src/controllers/torrent.js
> +        poster: 1,
`getTorrentsPage` gets a page of torrents (25) to display in lists (search, browse etc.). Only `fetchTorrent` which fetches a single torrent to display on `/torrent/[infoHash]` needs to include the image. Sorry for confusing naming

2023-10-12 16:15 UTC, Klaiment commented on api/src/controllers/torrent.js
> +        poster: 1,
fixed

2023-10-12 17:27 UTC, Klaiment commented
All done.

2023-10-26 20:39 UTC, CodeMeZone commented
Any ETA on this push?

2023-10-27 20:07 UTC, abiteman commented
Also looking at an update on a potential push.

2023-10-29 13:46 UTC, tdjsnelling commented
Sorry for the delay. Thanks for your changes, everything looks good now. Good job getting this implemented

2023-10-29 13:46 UTC, merged